### ISSUE TITLE
Unable to Deserialize TreeMap<byte[], byte[]>

### ISSUE THREAD

**Issue by poneill00** [Cascading/cascading.kryo#21]
Hey, I'm using Kryo to serialize a TreeMap<byte[],byte[]> (which is required when writing to HBaseTap with DynamicScheme).

Serialization seems to work, but I get the below error when DeSerializing
 Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: [B
  at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
  at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
  at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:610)
  at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:721)
  at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:134)
  at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:17)
  at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:626)
  at cascading.kryo.KryoDeserializer.deserialize(KryoDeserializer.java:37)
  at cascading.tuple.hadoop.TupleSerialization$SerializationElementReader.read(TupleSerialization.java:628)

**Comment by johnynek** [comment]
This project is pretty out of date.

I would recommend looking at:

https://github.com/twitter/chill/tree/develop/chill-hadoop

Set this to be your serialization class:
https://github.com/twitter/chill/blob/develop/chill-hadoop/src/main/java/com/twitter/chill/hadoop/KryoSerialization.java

and use:
https://github.com/twitter/chill/blob/develop/chill-java/src/main/java/com/twitter/chill/config/ConfiguredInstantiator.java#L85

with:
https://github.com/twitter/chill/blob/develop/chill-hadoop/src/main/java/com/twitter/chill/hadoop/HadoopConfig.java

to set your instantiator (the class that creates new Kryo instances).
